##############
#     SPRING
#############
spring:
  mvc:
    locale-resolver: fixed
    locale: pt_PT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

##############
#       DB
##############




